server:
  port: 7001

eureka:
  instance:
    hostname: eureka7001.com #服务端的实例名称
  client:
    register-with-eureka: false #false表示不向注册中心注册自己
    fetch-registry: false #flase表示自己就是注册中心，职责是维护服务实例，不需要取检索实例
    service-url:
      #设置与Eureka Server交互的资质查询服务和注册服务都需要依赖这个地址
#      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
      defaultZone: http://eureka7002.com:7002/eureka/
  server:
    enable-self-preservation: false #禁用自我保护模式
    #扫描失效服务的间隔时间（单位毫秒，默认是60*1000）即60秒
    eviction-interval-timer-in-ms: 2000